import csv
import functools
import json
import os
import sys

base_path = sys.argv[1]
path = f"{base_path}/identifiers/country-us/census_autogenerated"


def get_valid_ocdids(filename):
    result = []

    with open(f"{path}/{filename}.csv") as f:
        for ocdid, _, _, _ in csv.reader(f):
            result.append(ocdid)

    return result


def check_file(filename, ocdid_filename):
    filename = f"out/{filename}.geojson"
    if not os.path.exists(filename):
        return

    print(f"Checking {filename}")
    valid = get_valid_ocdids(ocdid_filename)

    with open(filename) as f:
        features = json.load(f)["features"]

    for feature in features:
        ocdid = feature["properties"]["OCDID"]
        if ocdid not in valid:
            print(f"{ocdid} is not valid!")


with open("data/fips.csv") as f:
    for fips, _, _ in csv.reader(f):
        check_file(f"sldl/{fips}", "us_sldl")
        check_file(f"sldu/{fips}", "us_sldu")
        check_file(f"congress/{fips}", "us_congressional_districts")
